name: GCP OIDC Auth Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  gcp-authentication:
    name: Authenticate to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/946313276556/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: finstream-github-deployer@fintech-data-platform-dev.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Verify GCP identity
        run: |
          gcloud auth list
          gcloud config set project fintech-data-platform-dev
          gcloud config get-value project